# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legs', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'scheduled'), (2, 'in_progress'), (3, 'completed')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.IntegerField(choices=[(1, 'male'), (2, 'female')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_ht_score', models.IntegerField(default=0)),
                ('away_ht_score', models.IntegerField(default=0)),
                ('home_ft_score', models.IntegerField(default=0)),
                ('away_ft_score', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('comments', models.CharField(blank=True, default='', max_length=500)),
                ('stage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='A', max_length=255)),
                ('last_name', models.CharField(default='B', max_length=255)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_birth', models.DateField(default=datetime.date(1976, 1, 1))),
                ('gender', models.IntegerField(choices=[(1, 'male'), (2, 'female')], default=1)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amh_api.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('last_stage', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'scheduled'), (2, 'in_progress'), (3, 'completed')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amh_api.Club')),
                ('level', models.ManyToManyField(to='amh_api.Level')),
                ('players', models.ManyToManyField(to='amh_api.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='amh_api.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amh_api.Competition'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='amh_api.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_a', to='amh_api.Referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_b', to='amh_api.Referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer', to='amh_api.Referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='timekeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timekeeper', to='amh_api.Referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amh_api.Venue'),
        ),
        migrations.AddField(
            model_name='competition',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amh_api.Level'),
        ),
        migrations.AddField(
            model_name='competition',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amh_api.Season'),
        ),
    ]
