# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amh_api', '0002_season_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
