# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amh_api', '0004_competition_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='referee_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_a', to='amh_api.Referee'),
        ),
        migrations.AlterField(
            model_name='match',
            name='referee_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_b', to='amh_api.Referee'),
        ),
        migrations.AlterField(
            model_name='match',
            name='scorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorer', to='amh_api.Referee'),
        ),
        migrations.AlterField(
            model_name='match',
            name='timekeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timekeeper', to='amh_api.Referee'),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amh_api.Venue'),
        ),
    ]
