# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amh_api', '0006_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='draws',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='goals_against',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='goals_for',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='lost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='wins',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
