# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amh_api', '0007_auto_20151207_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='amh_api.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.ManyToManyField(related_name='level', to='amh_api.Level'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='players', to='amh_api.Player'),
        ),
    ]
